CHANGELOG.md
tests/integration/test_uk_carbon_intensity.py
viadot/sources/uk_carbon_intensity.py

When testing the uk carbon intensity example I found out that it always returns one row.
The bug was caused by an badly indented return which exited the loop too early.
TODO: add info to changelog

🐛 Fix early return in json_data loop

---

CHANGELOG.md
viadot/task_utils.py

Small improvement to pandas' `to_csv()` as it requires all the directories in `path` to already be present. Now, we create them when needed.
This PR:

✨ `df_to_csv` now creates dirs if they don't exist

---

CHANGELOG.md
docker/Dockerfile

Fix for old SQL Servers still using TLS < 1.2
This PR:

🐛 Fix for old SQL Servers still using TLS < 1.2

---

CHANGELOG.md
viadot/flows/sap_to_duckdb.py
viadot/sources/sap_rfc.py
viadot/tasks/sap_rfc.py

Fixed `SAPRFC.to_df()` ignoring user-specified separator and always falling back to picking it automatically.
This PR:

🐛 Fixed `SAPRFC.to_df()` ignoring user-specified separator

---

CHANGELOG.md
viadot/sources/base.py
viadot/sources/sql_server.py

Adds support for SQL Server's custom `datetimeoffset` type. This allows the source to work with tables that contain datetime columns.
This PR:

✨ Add support for SQL Server's custom `datetimeoffset` type

---

CHANGELOG.md
tests/unit/test_utils.py
viadot/tasks/__init__.py
viadot/tasks/azure_sql.py
viadot/utils.py

Adds `AzureSQLUpsert` task for upserting a pandas DataFrame into AzureSQL.
Currently, this uses regular INSERT statement to insert records into the temp table. In the future, bulk method should also be supported.
This PR:

✨ Add `AzureSQLUpsert` task

---

CHANGELOG.md
viadot/utils.py

Fixes `get_flow_last_run_date()` incorrectly parsing the date
This PR:

🐛 Fix `get_flow_last_run_date()` incorrectly parsing the date

---

CHANGELOG.md
viadot/tasks/cloud_for_customers.py

Fixes c4c secret handling.
Tasks now correctly read the secret as the credentials, rather than assuming the secret is a container for credentials for all environments and trying to access specific key inside it. In other words, tasks now assume the secret holds credentials, rather than a dict of the form `{env: credentials, env2: credentials2}`
This PR:

Fix c4c secret handling

---

viadot/sources/salesforce.py
viadot/tasks/salesforce.py

Adds prod handling to `Salesforce` (`credential_secret`, possibility to specify `PROD` environment).
This PR:

Add production functionality to `Salesforce` source

---

CHANGELOG.md
viadot/sources/salesforce.py
viadot/tasks/__init__.py
viadot/tasks/salesforce.py

Improves error handling in `Salesforce` source by allowing to specify a `raise_on_error` parameter (only display a warning on failing rows otherwise).
This PR:

🥅 Improve error handling in `Salesforce` source

---

CHANGELOG.md
viadot/utils.py

Fixes `utils.gen_bulk_insert_query_from_df()` failing with > 1000 rows due to INSERT clause limit by chunking the data into multiple INSERTs
This PR:

🐛 Add chunking to overcome 1000 rows limit in INSERT clause

---

CHANGELOG.md
tests/unit/tasks/test_duckdb.py
tests/unit/test_duckdb.py
tests/unit/test_utils.py
viadot/flows/epicor_to_duckdb.py
viadot/flows/sap_to_duckdb.py
viadot/flows/sql_server_to_duckdb.py
viadot/task_utils.py
viadot/tasks/duckdb.py
viadot/utils.py

Added `if_empty` parameter in `DuckDBCreateTableFromParquet` task and in `EpicorToDuckDB`, `SAPToDuckDB`,
`SQLServerToDuckDB` . Added `check_if_empty_file()` and `handle_if_empty_file()` in `utils.py`
Added `map_dtypes_to_str` task in `utils.py` and added this to `EpicorToDuckDB`, `SAPToDuckDB`, `SQLServerToDuckDB`
When Parquet was empty (or had only one column `_viadot_downloaded_at_utc`) DuckDB couldn't upload file to DB because of column mismatch. Now there is an option to skip if file is empty
Added mapping to strings  before uploading data to DuckDB
This PR:

Empty parquet handling

---

CHANGELOG.md
viadot/sources/salesforce.py

Fixes log being printed too early in `Salesforce` source, which would sometimes cause a `KeyError`
This PR:

🐛 Fix log being printed too early

---

CHANGELOG.md
viadot/sources/salesforce.py

Fixed `raise_on_error` incorrect behavior when receiving incorrect return codes from Salesforce in `Salesforce.upsert()`.
This PR:

🐛 Fix `raise_on_error` incorrect behavior in some cases in `Salesforce.upsert()`

---

.dockerignore
docker/Dockerfile

Decreases Docker image size by adding a `.dockerignore` and turning off pip cache.
This PR:

Decrease Docker image size

---

CHANGELOG.md
viadot/flows/epicor_to_duckdb.py
viadot/flows/sap_to_duckdb.py
viadot/flows/sql_server_to_duckdb.py

Changed tasks order in `EpicorOrdersToDuckDB`, `SAPToDuckDB` and `SQLServerToDuckDB` - casting DF to string before adding metadata
`viadot_downloaded_at` will be TIMESTAMP instead of VARCHAR in output table
This PR:

Change casting order

---

CHANGELOG.md
tests/integration/tasks/test_azure_data_lake.py
viadot/flows/adls_to_azure_sql.py
viadot/sources/azure_data_lake.py
viadot/tasks/azure_data_lake.py

Now `AzureDataLake` class contains `find()` method that list all files and folders inside provided patch.
Also we modified `AzureDataLakeList` task and now it's able to show recursive directory.
It may be important because while data ignestion process e.g if there will be situation like:
`c4c/account/2022/06/27/account.csv`
`c4c/account/2022/06/27/tickets.csv`
`c4c/account/2022/06/28/account.csv`
`c4c/account/2022/06/28/tickets.csv`
`c4c/account/2022/06/29/account.csv`
`c4c/account/2022/06/30/account.csv`
and we would like to load only account.csv file we can genereate list of path for file with specific name.
`list_in_adls = AzureDataLakeList()
valid_paths = list_in_adls.run(
path="raw/tests/alds_test_new_fnc",
recursive=True,
file_to_match = 'final_df2.csv', …

Add `find` path support to AzureDataLake class

---

viadot/flows/outlook_to_adls.py
viadot/tasks/outlook.py

A time-out limitation is added to avoid infinite Task execution. This is built-in argument of Task class in prefect V1.
Very important, due to the fact that the Outlook flow can be running for days if it is not working properly.
This PR:

⚡️added timeout limitation to run OutlookToDF class

---

CHANGELOG.md
viadot/sources/databricks.py

Removed the `env` param from `Databricks` source, as user can now store multiple configs for the same source using different config keys.
This PR:

🔥 Databricks - remove `env` parameter

---

CHANGELOG.md
viadot/tasks/duckdb.py
viadot/tasks/sap_rfc.py

Added timeout to `DuckDBQuery` and `SAPRFCToDF`
Default timeout helps with flows that run for a long time but are not supposed to do that
This PR:

✨ Added timeout to `DuckDBQuery` and `SAPRFCToDF`

---

CHANGELOG.md
tests/unit/test_databricks.py
viadot/sources/databricks.py

Fixed a bug in `create_table_from_pandas` where using `if_exists="replace"`  does not work.
This fix allows users to use the `replace` option to replace tables that already exist.
This PR:

🐛 Databricks bug fix

---

viadot/sources/redshift_spectrum.py
viadot/sources/s3.py

Allows specifying AWS Region and fixes errors in `RedshiftSpectrum` source due to this credential not being read correctly.
This PR:

🐛Fix credential handling to handle AWS region

---

viadot/sources/redshift_spectrum.py
viadot/sources/s3.py

Fixes logger being called before initialization in `S3` and `RedshiftSpectrum` sources.
This PR:

🐛 Fix logger being called before initialization

---

CHANGELOG.md
tests/integration/flows/test_adls_to_azure_sql.py
viadot/flows/adls_to_azure_sql.py
viadot/tasks/azure_sql.py

Before adding this new feature, if the user passes a non-sorted dtypes argument like in the ADLS file, it creates an unsorted data frame to upload to Azure SQL table.
Also added more descriptions to azure_sql.py about how the credentials are loaded.
Not relevant right now, because all our flows are well built but it would be important for any user that is not aware of the problem.
This PR:

Check if dtypes is sorted as in ADLS file

---

CHANGELOG.md
viadot/flows/genesys_to_adls.py
viadot/tasks/genesys.py

Added `view_type_time_sleep` in Genesys type `queue_performance_detail_view` to modify the time to wait for Genesys' response. If you don't leave Genesys to generate reports, then, when retrieving data you could not download some queues. There are more than 100 queues, so the probability is quite high having the issue.
Very important for incoming project release.
This PR:

Genesys waiting time extension

---

CHANGELOG.md
tests/conftest.py
tests/unit/test_s3.py
viadot/sources/s3.py

- Fixed S3 Source Methods from_df and to_df
- Changed methods from_df, to_df and rm to enable user the possibility to input a list of files
- Added methods upload, download to enable user the possibilty of uploading and downloading files to S3
- erased dataset parameter in from_df and to_df methods
-        parameter is used for partitioning 
-        errors resulting from not including further parameters are described  below
1. from_df is saving parquets files as snappy.parquet, this format is not supported by to_df yet
2. to_df needs at least filename_prefix defined to work (see awsrangler package: s3/_read_parquet.py:792)
- enhancement issue is opened for including partitioning functionality in the future #609 
- enables user to use functions with input as list of files instead of …

🐛 Fixed and Extended S3 Source

---

CHANGELOG.md
viadot/flows/adls_to_azure_sql.py

Added a new parameter `apply` to the task `check_dtypes_sort`  that is in the flow `adls_to_azure_sql.py`. With this new parameter, the user could decide to make use of this characteristic or not.
Some important to avoid failing some flows.
This PR:

`apply` parameter to check dtypes.

---

CHANGELOG.md
tests/integration/flows/test_bigquery_to_adls.py
tests/integration/tasks/test_bigquery.py
viadot/flows/bigquery_to_adls.py
viadot/tasks/bigquery.py

A new parameter was added to the `BigQueryToADLS` flow and `BigQueryToDF` task. It was a request from another team. Previously it wasn't possible to filter the dataset and enter the custom SQL query.
The new parameter is added to be able to enter custom SQL queries. Previously only providing a list of columns and filtering by date was possible.
This PR:

Bigquery new `query` parameter

---

tests/unit/test_exchange_rates.py

The following PR fixes a bug in one of the tests in the ExchangeRates source. This is exactly the test `test_to_df_values`. The problem was caused by the fact that when the to_df() method is called on the object, 2 additional columns are added, so the data was not identical to the expected ones.
After the fix all tests will work.
This PR:

Fixed bug in exchange rates unit tests

---

CHANGELOG.md
tests/unit/test_databricks.py
viadot/sources/databricks.py

The issue (#672 ) has been fixed. The bug prevented overwriting a table in Databricks whose column names were not saved in "snake_case".  The fix was made by adding a call to the function `df_snakecase_column_names()` on the DataFrame inside the `_full_refresh()` function, which is executed when the `replace="True"` parameter is set.
This is important because this bug could cause errors in workflows in the future.
This PR:

Databricks snakecase column bug

---

viadot/sources/s3.py

Changed `chunked` to `chunksize` in `wr.s3.read_csv()` as per [awswrangler.s3.read_csv](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.read_csv.html) docs
Note: For `wr.s3.read_parquet()` it should be kept as `chunked` as per [awswrangler.s3.read_parquet](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.read_parquet.html) docs

🚑 Fixed typo in `chunksize` parameter name

---

CHANGELOG.md
viadot/sources/mindful.py
viadot/tasks/mindful.py

Mindful API has undergone a change in its structure. Since three weeks ago we are not able to access the API by adding credentials in the header. The solution given by the HCL support team is using `auth` parameter in the `request` function, and it was implemented in the present PR.
On the other hand, Instead of `Bearer` authentication, a new `Basic` authentication is used. The client chose this new way of authentication to avoid future problems with archived credentials after 90 days.
Required by client. Very important.
This PR:

Mindful auth

---

viadot/tasks/cloud_for_customers.py

📝 updated documentation

---

CHANGELOG.md
viadot/sources/bigquery.py

Decorator is added to the Bigquery source class. It's applied on the `query_to_df()` method. Every extraction from now on will have an additional column `_viadot_source` with value `BigQuery`
Need to include the `_viadot_source` column in tables in the future data catalog
This PR:

Add `_viadot_source` column to `BigQuery`

---

tests/integration/flows/test_prefect_logs.py
tests/integration/tasks/test_bigquery.py
tests/integration/test_mindful.py

Fix tests that are failing
This PR:

Correct tests before release

---

CHANGELOG.md
viadot/task_utils.py

Task to validate the data on DataFrame level. New validation on data extraction phase.
```
tests:
- `column_size`: dict{column: size}
- `column_unique_values`: list[columns]
- `column_list_to_match`: list[columns]
- `dataset_row_count`: dict: {'min': number, 'max', number}
- `column_match_regex`: dict: {column: 'regex'}
```
It is important to add this task/function to every extraction flow to be able to validate the data on the DF level.
By doing that we can avoid situations when wrong data are sent to ADLS.
This PR:

Added `validate_df` task to task_utils

---

tests/integration/flows/test_eurostat_to_adls.py
viadot/flows/eurostat_to_adls.py

Added optional parameter `validate_df_dict` to EurostatToADLS class to run tests on extracted data frame from the source.
This PR:
- [x ] adds/updates tests (if appropriate)
- [x ] adds/updates docstrings (if appropriate)

added `validate_df` task to EurostatToADLS flow

---

tests/integration/flows/test_mysql_to_adls.py
viadot/flows/mysql_to_adls.py

Added `validate_df` task to MySqlToADLS flow as on optional parameter: `validate_df_dict`. It allows to verify if the output dataframe matches expectations applied in tests.
This PR:

added `validate_df` task to MySqlToADLS flow

---

tests/integration/flows/test_supermetrics_to_adls.py
viadot/flows/supermetrics_to_adls.py

Added validate_df task to `SupermetricsToADLS` class to let user define tests for validating the output dataframe.
This PR:

added `validate_df` task to `SupermetricsToADLS` flow

---

tests/integration/flows/test_hubspot_to_adls.py
viadot/flows/hubspot_to_adls.py

added df_validation to HubspotToADLS

---

tests/integration/flows/test_bigquery_to_adls.py
viadot/flows/bigquery_to_adls.py

- Added `validate_df_dict` parameter to `BigQueryToADLS` flow
- Added tests for the new parameter in the `BigQueryToADLS` flow
New functionality to check the data
This PR:

Add `validate_df` task  to `BigQueryToADLS` flow

---

viadot/flows/genesys_to_adls.py
viadot/tasks/genesys.py

Added new parameter to flow and task
data validation
This PR:

Genesys validate_df

---

CHANGELOG.md
tests/integration/test_sharepoint.py
viadot/flows/__init__.py
viadot/flows/sharepoint_to_adls.py
viadot/sources/__init__.py
viadot/sources/sharepoint.py
viadot/tasks/__init__.py
viadot/tasks/sharepoint.py
viadot/utils.py

New connector to extract data from MS Sharepoint lists
This PR:

Sharepoint list connector

---

viadot/flows/aselite_to_adls.py
viadot/flows/bigquery_to_adls.py
viadot/flows/cloud_for_customers_report_to_adls.py
viadot/flows/customer_gauge_to_adls.py
viadot/flows/eurostat_to_adls.py
viadot/flows/hubspot_to_adls.py
viadot/flows/mediatool_to_adls.py
viadot/flows/mysql_to_adls.py
viadot/flows/outlook_to_adls.py
viadot/flows/salesforce_to_adls.py
viadot/flows/sap_bw_to_adls.py
viadot/flows/sap_rfc_to_adls.py
viadot/flows/sharepoint_to_adls.py
viadot/flows/supermetrics_to_adls.py
viadot/flows/vid_club_to_adls.py

Added  line 
if self.validate_df_dict:
df_with_metadata.set_upstream(validation_task, flow=self)
to keep task ordered 
This PR:

added order for validation_task in viadot flows

---

CHANGELOG.md
viadot/sources/genesys.py
viadot/tasks/genesys.py

Simply added the new view type `agent_interaction_view_type` into `genesys` source code.
Required by client.
This PR:

Genesys agent interaction view type

---

CHANGELOG.md
requirements.txt
tests/integration/tasks/test_tm1.py
tests/integration/test_tm1.py
viadot/sources/__init__.py
viadot/sources/tm1.py
viadot/tasks/__init__.py
viadot/tasks/tm1.py

Source and task class for TM1. Download is based on cube and view name
Added new data source
This PR:

Added TM1 connector

---

CHANGELOG.md
viadot/flows/bigquery_to_adls.py

A new parameter `set_prefect_kv` is added to specify when to run the `set_key_value` function and set a new key-value pair on Prefect.
To reduce the number of pairs created, the parameter is set to `False`. If a new pair is needed the parameter can be set as `True` in the flow.
This PR:

⚡️ Added `set_prefect_kv` parameter to `BigQueryToADLS` flow

---

tests/integration/flows/test_sharepoint_to_adls.py
viadot/flows/sharepoint_to_adls.py

- Merged `path` and `adls_file_name` arguments into `file_name` in SharepointListToADLS class.
- Added to_csv functionality to SharepointListToADLS.
This PR:

Sharepoint list to csv

---

tests/integration/test_vid_club.py
viadot/flows/vid_club_to_adls.py
viadot/sources/vid_club.py
viadot/tasks/vid_club.py

Url for api endpoint  was changed, because parameters for endpoints got changed and value 'all' for parameter 'region' is no longer valid. Instead by default parameter 'region' (for job, company and survey) isn't used at all.

Fix url in vidclub connector

---

tests/unit/test_utils.py
viadot/sources/sharepoint.py
viadot/tasks/genesys.py
viadot/utils.py

Added tests to improve coverage of `utils.py` file
To have better test coverage of viadot code.
This PR:

Improve `utils.py` test coverage

---

tests/integration/flows/test_bigquery_to_adls.py
tests/integration/flows/test_mysql_to_adls.py
tests/integration/flows/test_salesforce_to_adls.py
tests/integration/flows/test_vidclub_to_adls.py
tests/integration/tasks/test_vid_club.py

Fix failed tests before release
This PR:

Fix tests before release 

---

.github/workflows/publish_to_pypi.yml

This is a new method based on OIDC, enforced by PyPI, which recently deprecated using username/password.
This action also has the benefit of using the `dyvenia` PyPI account rather than `acivitillo`.
This PR:

Update PyPI pipeline to use Trusted Publishing

---

CHANGELOG.md
tests/integration/flows/test_adls_to_azure_sql.py
viadot/flows/adls_to_azure_sql.py

Added validate_df func into ADLSToAzureSQL flow for potential test on level ADLS-to-AzureSQL
Genesys connector needs validation on this level of data flow
This PR:

`validate_df` implementation to `ADLSToAzureSQL`

---

setup.py

Added missed dependencies to `viadot` PyPI package. These resolves issue with missing packages in `prefect-viadot` despite the installation `viadot` package from PyPI. Now `requirements.txt` file is linked with `steup.py` so we don't have to do changes in both files.

➕ Add missing dependencies in `setup.py`

---

CHANGELOG.md
requirements.txt

The PR containing changes in requirements.txt file. Dbt-sqlserver were upgraded to djagoda's fork in order to fix bug in dbt.
It is important because without it some of the Transform&Catalog flows will be failing on Prefect due to bug in current version of dbt-sqlserver. Linked issue: #854 
This PR:
- [X ] follows the guidelines laid out in `CONTRIBUTING.md`
- [X ] links relevant issue(s)
- [] adds/updates tests (if appropriate)
- [] adds/updates docstrings (if appropriate)
- [X ] adds an entry in `CHANGELOG.md`

🐛 Changed dbt packages in requirements.txt

---

CHANGELOG.md
viadot/tasks/azure_sql.py

The `if_exist` parameter definition was malformed. Now is fixed and set up to `fail` by default.
Not urgent, but probably important.
This PR:

Fixed the `if_exists` parameter in `CreateTableFromBlob` task

---

src/viadot/sources/sap_rfc.py

Small fix to prevent partitioned queries from crashing when there is no data to return from SAP
Fixing issue  #886 
This PR:

🐛 Fixing crash when no data returned in `SAPRFCV2`

---

tests/integration/tasks/test_sap_rfc_to_df.py
tests/integration/test_sap_rfc.py
viadot/sources/sap_rfc.py

Fixing bug related to tests after previous changes and changed logger.warning info in source . 
This PR:
- [X ] follows the guidelines laid out in `CONTRIBUTING.md`
- [ X] adds/updates tests (if appropriate)

🐛 Fix bug related to logger.warning and tests in sap_rfc source 

---

CHANGELOG.md
src/viadot/sources/sharepoint.py
tests/unit/test_sharepoint.py

Added `_convert_all_to_string_type` and `_empty_column_to_string` to convert all types to string or object.
It was important to cast empty columns to string as the type of empty column was `object`. Pandas was showing the error.
This PR:

Sharepoint convert data types to string

---

.github/workflows/detect-and-tag-new-version.yml
pyproject.toml

This time found this https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow which uses `GH_TOKEN` env var rather than `GITHUB_TOKEN`, which is used in various other places.

Fix release trigger workflow

---

.github/workflows/detect-and-tag-new-version.yml
pyproject.toml

Fix the missing `v` prefix, cause GitHub release to not be created.

🐛 Fix release workflow release tag

---

src/viadot/sources/s3.py

Added get_page_iterator function to S3. It will help to iterate on directories and filter objects.
This function was missing. There is a need to use it.
Example:
```
iterator = get_page_iterator(bucket_name= "bucket_name", directory_path="dir_name/dir", **kwargs)
```
This PR:

✨ Add `get_page_iterator()` method to `S3`

---

pyproject.toml
requirements-dev.lock
requirements.lock

Should hide `CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.`, as per https://github.com/paramiko/paramiko/issues/2419#issuecomment-2340435799
This PR:

⬆️ Bump `paramiko` to 3.x to hide deprecation warnings

---

src/viadot/sources/cloud_for_customers.py

Added report_url argument.
Deployments are not working without this argument
This PR:

✨ Add `report_url` param to `CloudForCustomers.extract_records()`

---

src/viadot/sources/sap_rfc.py

Reverts dyvenia/viadot#1065 as in some cases it creates NULL values

Revert "🐛 Fix whitespace removal causing duplicates in `SAPRFCV2`"

---

src/viadot/exceptions.py
src/viadot/sources/s3.py

Added a new method to calculate the size of single or multiple objects in S3.
This functionality was missing. It is used in the other flow. It was important to move it to the source class.
This PR:

✨ Add `get_object_sizes` method to S3 source

---

src/viadot/orchestration/prefect/utils.py
tests/unit/orchestration/prefect/test_utils.py

Introducing a class to handle pendulum DateTimes or time-related patterns within a provided text, replacing dynamic date marker with actual dates.
The supported patterns include:
- "today"
- "yesterday"
- "this_month"
- "last_month"
- "this_year"
- "last_year"
- "now_time"
- "last_day_previous_month"
- "last day of month": e.g., "last day of February 2020"
- "X years ago": e.g., "3 years ago" , refers to only the year of the day X years ago
- "X years/months/days ago full date": e.g., "3 years ago full date", refers to a given date X units ago in dynamic_date_format
- "last X years/months": e.g., "last 10 months", refers to a data range of the months in 'YMM' format
- "Y years from X": e.g., "10 years from 2020", refers to a data range of the year numbers from a specified year
- "first X …

✨ Add DynamicDateHandler class

---

README.md

Updated rye installation link - old domain get obsolete
Closes  [#641](https://github.com/dyvenia/werfen-project/issues/641)
This PR:

Rye url change

---

.gitignore
pyproject.toml
requirements-dev.lock
requirements.lock
src/viadot/sources/sap_rfc.py
tests/unit/test_sap_rfc_2.py

Seems like SAP returns columns with different amount of whitespaces - ideally SAP server should always add whitespaces , that the amount of characters matches the declared data type in SAP table definition. 
However, after some investigation , looks like from every n-th SAP request, it is trimming all whitespaces or messing the number of added ones - which could lead to wrongly merged SAP responses using unique columns as the merge key.
In this PR there is a solution, that, for each UNIQUE columns, checks the returned SAP table metadata to obtain what is the declared data type ( and the characters amount ) , then it checks what is the received character amount and adds whitespaces to match the declared one.
Whitespaces are added using vector/matrix approach which doesn't slow down the …

🐛 [BUGFIX] For `SAPRFCV2` adding whitespaces to match sub - queries

---

pyproject.toml
requirements-dev.lock
requirements.lock
src/viadot/orchestration/prefect/flows/__init__.py
src/viadot/orchestration/prefect/flows/tm1_to_parquet.py
src/viadot/orchestration/prefect/tasks/__init__.py
src/viadot/orchestration/prefect/tasks/tm1.py
src/viadot/sources/__init__.py
src/viadot/sources/tm1.py
tests/unit/test_tm1.py

TM1 connector migration from viadot 1 to viadot 2.
Update docs in Business Core Prefect task.
Required by the migration project.
This PR:

✨ Add `TM1` source and Prefect tasks

---

src/viadot/orchestration/prefect/tasks/mediatool.py
src/viadot/sources/mediatool.py
tests/integration/orchestration/prefect/flows/test_mediatool.py
tests/unit/test_mediatool.py

Prefect migration 2.0 backlog changes for Mediatool, related to issues:
- #1062 
- #1061 
- #1060 
- #1049 
Fixing bug, clean code
This PR:

♻️ Refactor Mediatool, 2.0 backlog issues

---

.secrets.baseline
pyproject.toml
src/viadot/orchestration/prefect/flows/transform_and_catalog.py
src/viadot/orchestration/prefect/tasks/s3.py

✨ Add a task to dump dbt test results to s3

---

src/viadot/orchestration/prefect/utils.py
tests/unit/orchestration/prefect/test_utils.py

Addition of two markers for data ranges. One returns a data range from a given year until now, and another from a given year until last_year. They allow having separate deployment schedules for older years than last_year.
- "years_from_x_until_now_included": e.g. "years_from_2019_until_now_included",
refers to a date range of the years from a given year
until the current year included
- "years_from_X_until_Y_years_ago": e.g., "years_from_2019_until_2_years_ago",
refers to a date range of the years from a given year until last year
(not including last year)
Test:
[1](https://app.prefect.cloud/account/8e3c357b-643a-46d2-b41f-68414816c39b/workspace/d8908744-1c40-4929-9235-693a82b58fb2/deployments/deployment/35b60676-0093-4ebf-9348-028fc0910bc4) …

Dynamic date add parameter

---

src/viadot/orchestration/prefect/flows/sap_to_redshift_spectrum.py
src/viadot/orchestration/prefect/flows/sharepoint_to_redshift_spectrum.py
src/viadot/utils.py
tests/unit/test_utils.py

- Passes the tests parameter from the sap_to_redshift_spectrum and sharepoint_to_redshift_spectrum flows to their respective tasks, enabling test functionality.
- Fixes the validate function to raise an error when validation conditions aren't met.
This PR:

✨ Add `tests` param to `sap_to_redshift_spectrum` and `sharepoint_to_redshift_spectrum` flows

---

src/viadot/orchestration/prefect/flows/sharepoint_list_to_redshift_spectrum.py

Simple bug fix for the param name in the flow.
It has to be changed from `table_name` to `table`
This PR:

🐛 Changed parameter name from table_name to table

---

pyproject.toml
src/viadot/sources/s3.py

Added describe_objects function to S3 class.
In the other repo, we use `wr.s3.describe_objects`. It's added to the S3 connector to replace this operation.
This PR:

✨ Add `describe_objects` function to S3 connector

---

pyproject.toml
requirements-dev.lock
requirements.lock

Due to known issue on dbt side, we need to pin `dbt-adapters` to `1.14.3`. 
`dbt-adapters` in version `1.16.0` throws following error when run on incremental models with `delete+insert` strategy.
NOTE from @marcinpurtak : If the model is created for a first time it will not fail as there is nothing to update. Make tests for incremental with 2 times run to make sure that it runs good. The reason for the error is that the new version of the dbt-adapters adds an ** DBT_INTERNAL_SOURCE alias to the delete query** which is not valid for the Redshift db engine.
Example:
```
delete from "werfendb"."sandbox_intermediate"."int_trials" as DBT_INTERNAL_DEST
where (id) in (
select distinct id
from "int_trials__dbt_tmp134038254413" as DBT_INTERNAL_SOURCE
);
```
2 errors occurs
```
syntax error at or …
```

📌 Pin `dbt-adapters` to `1.14.3`

---

src/viadot/sources/smb.py
tests/unit/test_smb.py

A new function, `_add_prefix_to_file_name`, has been added to enable differentiating files that share the same names but reside in different folders within the root server path.
This function is important because it prevents accidental overwriting by ensuring that files with identical names from different folders can be uniquely identified when uploaded or copied.
This PR:

✨ Added `_add_prefix_to_file_name` function to SMB

---

pyproject.toml
src/viadot/sources/smb.py

There is a bug in SMB connector. Reading entry stat is outside try block. When files are removed from the server the flow is getting `smbprotocol.exceptions.SMBOSError: [Error 2] [NtStatus 0xc0000034] No such file or directory:` Error.
It is handled in the try - except block.
It has to be fixed to fix the SMB ingestion pipeline.
This PR:

🐛 Moved getting entry `stat` into `try` block - SMB
