dyvenia/viadot

- requirements.txt
> Revert "Adam"

- CHANGELOG.md
- mkdocs.yml
Moved task library page to topbar
Increases task lib visibility
This PR:
> 🚚 Moved task library page to topbar

- .gitignore
- CHANGELOG.md
- README.md
Adding some style guidelines for collaborators.
This PR:
> Style guidelines

- tests/integration/test_azuresql.py
> Fix `SQL.create_table()` with `if_exists` set to `"append"` test

- README.md
> Docs add priviledge command

- README.md
- created a section for local setup (before the run sections
-  How to contribute section update
> 📝 Add local setup section and update contribution guide in README.md 

- CHANGELOG.md
- viadot/flows/adls_to_azure_sql.py
- viadot/flows/supermetrics_to_adls.py
…cs_to_adls
- ADLSToAzureSQL - fixed path to csv issue. 
- SupermetricsToADLS - fixed local json path issue. 
This PR:
> Supermetrics hot fix

- CHANGELOG.md
- requirements.txt
- tests/integration/test_sharepoint.py
- tests/unit/test_task_utils.py
- viadot/exceptions.py
- viadot/flows/__init__.py
- viadot/flows/cloud_for_customers_to_adls.py
- viadot/flows/sharepoint_to_adls.py
- viadot/flows/supermetrics_to_adls.py
- viadot/sources/__init__.py
- viadot/sources/sharepoint.py
- viadot/task_utils.py
- viadot/tasks/__init__.py
- viadot/tasks/sharepoint.py
> Sharepoint

- tests/integration/test_cloud_for_customers.py
- viadot/flows/cloud_for_customers_report_to_adls.py
- viadot/sources/__init__.py
- viadot/sources/base.py
- viadot/sources/cloud_for_customers.py
- viadot/task_utils.py
> Fix c4c credentials

- CHANGELOG.md
- tests/integration/test_supermetrics.py
- tests/unit/test_supermetrics.py
- viadot/exceptions.py
- viadot/sources/supermetrics.py
> Fix ga get columns

- tests/integration/test_uk_carbon_intensity.py
> ♻️ Sped up the test

- tests/integration/test_sharepoint.py
- viadot/sources/sharepoint.py
> Improve sharepoint creds handling

- CHANGELOG.md
- tests/integration/test_cloud_for_customers.py
- tests/unit/test_cloud_for_customers.py
- viadot/sources/cloud_for_customers.py
> ♻️  Improved credential handling

- CHANGELOG.md
- viadot/sources/cloud_for_customers.py
Fixed authorization issue `CloudForCustomers` source
C4C hotfix
This PR:
> C4c auth fix

- CHANGELOG.md
- tests/integration/test_azuresql.py
- viadot/flows/adls_to_azure_sql.py
- viadot/sources/base.py
- viadot/sources/sharepoint.py
- viadot/tasks/azure_sql.py
A new option has been added which allows you to delete data from a table without deleting the table and creating it.
To avoid constantly renewing access to tables (which are removed with the "replace" option) for users.
This PR:
> Add `delete` option to `Source.create_table()`'s `if_exists` parameter

- CHANGELOG.md
- docker/Dockerfile
- requirements.txt
- viadot/examples/hello_world.py
> Pin prefect

- viadot/utils.py
Fixed utils.py docstring for `handle_api_response`
The previous version was misleading. 
This PR:
> 📝 Fixed utils docstring

- .github/workflows/build.yml
- .gitignore
- CHANGELOG.md
- docker/Dockerfile
- requirements.txt
- setup.py
- tests/integration/test_sap_rfc.py
- viadot/examples/sap_rfc/Dockerfile
- viadot/examples/sap_rfc/README.md
- viadot/examples/sap_rfc/docker-compose.yml
- viadot/examples/sap_rfc/requirements.txt
- viadot/sources/__init__.py
- viadot/sources/sap_rfc.py
- viadot/tasks/__init__.py
- viadot/tasks/sap_rfc.py
> New source `SAPRFC` + new task `SAPRFCToDF`

- CHANGELOG.md
- tests/integration/flows/test_sap_to_duckdb.py
- viadot/flows/__init__.py
- viadot/flows/sap_to_duckdb.py
- viadot/tasks/sap_rfc.py
Adding  new flow `SAPToDuckDB` for moving data from SAP to DuckDB.
This PR:
> New flow `SAPToDuckDB`

- CHANGELOG.md
- tests/unit/test_duckdb.py
- viadot/sources/duckdb.py
> 🔥 Change `DuckDB().con` to no longer be a singleton

- CHANGELOG.md
- viadot/flows/adls_to_azure_sql.py
- viadot/tasks/azure_sql.py
Fixing issues connected within `ADLSToAzureSQL` 
Fixing crucial issues
This PR:
> 🐛 Fixed to_csv and CheckColumnOrder + changelog

- CHANGELOG.md
- viadot/sources/duckdb.py
- viadot/tasks/__init__.py
- viadot/tasks/duckdb.py
Added new taskk `DuckDBToDF` for pulling data from DuckDB into a pandas DataFrame.
This PR:
> Task `DuckDBToDF`

- CHANGELOG.md
- tests/unit/flows/test_duckdb_transform.py
- tests/unit/test_duckdb.py
- viadot/flows/__init__.py
- viadot/flows/duckdb_transform.py
- viadot/sources/duckdb.py
- viadot/tasks/duckdb.py
Added `DuckDBTransform` flow for running transform (as in eTl) queries on DuckDB.
This PR:
> Flow `DuckDBTransform`

- viadot/examples/sap_rfc/Dockerfile
- viadot/examples/sap_rfc/build.sh
Adds HTTP proxy to SAP RFC example Dockerfile & changes base image to `viadot:dev`
This PR:
> 🚸 Add HTTP proxy to SAP RFC example

- CHANGELOG.md
- viadot/task_utils.py
`df_to_parquet()` task now creates directories if needed
This PR:
> ♻️ `df_to_parquet()` task now creates directories if needed

- CHANGELOG.md
- viadot/flows/__init__.py
- viadot/flows/adls_to_azure_sql.py
- viadot/flows/duckdb_to_sql_server.py
- viadot/sources/sql_server.py
- viadot/task_utils.py
- viadot/tasks/__init__.py
- viadot/tasks/bcp.py
- viadot/tasks/sql_server.py
Adding `DuckDBToSQLServer` flow
This PR:
> ✨ Add `DuckDBToSQLServer` flow

- CHANGELOG.md
- viadot/sources/sap_rfc.py
Add several more separators to check for automatically in `SAPRFC.to_df()`.
This PR:
> 🚸 Add several more separators to check for automatically

- CHANGELOG.md
- requirements.txt
> ⬆️ Upgraded `duckdb` version to 0.3.2

- viadot/flows/duckdb_to_sql_server.py
Now there are only two options:
a) user provides all data types
b) user provides no data types and types are automatically inferred
This PR:
> 💄 Optimize type inference in  flow

- CHANGELOG.md
- viadot/utils.py
This adds `get_flow_last_run_date` util function
This PR:
> Add flow last run date util

- CHANGELOG.md
- viadot/tasks/cloud_for_customers.py
Adds retries to C4C tasks (3 by default)
This PR:
> ♻️ Add retries to C4C tasks

- CHANGELOG.md
- viadot/tasks/cloud_for_customers.py
Adds `chunksize` parameter to `C4CToDF` task to allow pulling data in chunks
This PR:
> ✨ Add `chunksize` parameter to `C4CToDF` task

- CHANGELOG.md
- viadot/tasks/bcp.py
Adds `chunksize` parameter to `BCPTask` task to allow more control over the load process
This PR:
> ✨ Add `chunksize` parameter to `BCPTask` task

- CHANGELOG.md
- viadot/tasks/__init__.py
- viadot/tasks/azure_sql.py
Adds `AzureSQLToDF` task
This PR:
> ✨ Add `AzureSQLToDF` task

- requirements.txt
Added necessary dependencies. 
This PR:
> ➕ added sendgrid and google-cloud

- CHANGELOG.md
- viadot/task_utils.py
Fixes`df_clean_column` modifying input DataFrame
This PR:
> Fix `df_clean_column`

- CHANGELOG.md
- tests/integration/tasks/test_task_utils.py
- tests/unit/test_task_utils.py
- viadot/task_utils.py
- viadot/utils.py
Added function custom_state_handler that send mail notification using custom smtp server
This PR:
> custom state handler with mail notifier

- viadot/task_utils.py
Fixed hardcoding issue
Fixed hardcoding issue
This PR:
> 🐛 Fixed hardcoding issue

- tests/integration/tasks/test_prefect.py
- viadot/tasks/__init__.py
- viadot/tasks/prefect_date_range.py
Fixed finding time_schedule value
For the GetFlowNewDateRange Task to run properly.
This PR:
> Fixed finding time_schedule value

- CHANGELOG.md
- viadot/flows/cloud_for_customers_report_to_adls.py
- viadot/sources/cloud_for_customers.py
- viadot/tasks/cloud_for_customers.py
Adds C4C secret handling to `CloudForCustomersReportToADLS` flow (`c4c_credentials_secret` parameter)
This PR:
> ✨ Add C4C secret handling to `CloudForCustomersReportToADLS` flow

- viadot/sources/salesforce.py
- viadot/tasks/salesforce.py
Regarding issue #373 
This PR:
> ✨ Batch upsert to Salesforce source

- viadot/utils.py
Adds one more catch to `gen_bulk_insert_query_from_df` util
This PR:
> 🐛 Add one more catch to `gen_bulk_insert_query_from_df` util

- tests/integration/tasks/test_salesforce.py
- viadot/sources/salesforce.py
> 🐛 Fix salesorce upsert INVALID FIELD bug

- CHANGELOG.md
- viadot/examples/sap_rfc/Dockerfile
- viadot/examples/sap_rfc/build.sh
Adds complete proxy settings in `SAPRFC` example
This PR:
> ✨ Add complete proxy settings in `SAPRFC` example

- viadot/examples/sap_rfc/Dockerfile
- viadot/examples/sap_rfc/requirements.txt
Updated SAP RFC example Dockerfile with HTTPS proxy and some file permission workarounds.
This PR:
> Updated the example Dockerfile for SAP RFC

- tests/integration/tasks/test_salesforce.py
- tests/integration/test_salesforce.py
- viadot/sources/salesforce.py
> Revert "Fix upsert error handling"

- tests/integration/flows/test_mysql_to_adls.py
- tests/integration/tasks/test_bigquery.py
- tests/integration/test_bigquery.py
- viadot/flows/mysql_to_adls.py
Correct the code in the viadot and tests to fix the tests.
Pass the tests.
This PR:
> Fix tests for release 4_4

- CHANGELOG.md
- tests/integration/flows/test_salesforce_to_adls.py
- tests/integration/tasks/test_salesforce.py
- viadot/flows/__init__.py
- viadot/flows/salesforce_to_adls.py
- viadot/task_utils.py
- viadot/tasks/__init__.py
- viadot/tasks/salesforce.py
The task is to create `SalesforceToDF` task for downloading the data from Salesforce and `SalesforceToADLS` flow.
There are tasks for uploading the data to Salesforce. A task for downloading the data is needed. Additionally, there is no flow for downloading the data to ADLS.
This PR:
> Add SalesforceToADLS flow

- CHANGELOG.md
- viadot/sources/epicor.py
- viadot/utils.py
Added handling POST requests in `handle_api_response()` and added it to `Epicor` source
`Epicor` can use function from `utils.py`  
This PR:
> Handling POST in utils

- CHANGELOG.md
- viadot/exceptions.py
- viadot/sources/sap_rfc.py
Changed `SAPRFC` source to process query that exceeds characters per row limit.
There is possibility to select more columns in than SAP_RFC limit allows
This PR:
> SAPRFC() characters per row limit

- viadot/tasks/bcp.py
Changed default log file path
Fixing error
This PR:
> 🐛 Changed default path

- CHANGELOG.md
- tests/integration/tasks/test_databricks.py
- viadot/sources/databricks.py
Added the rollback feature to the Databricks source.
The ability to rollback is crucial during testing, and is a great feature in general, in case an incorrect/accidental operation is done on the table.
This PR:
> Added rollback feature, improved comments formatting

- CHANGELOG.md
- tests/integration/tasks/test_azure_data_lake.py
- tests/integration/test_sharepoint.py
- viadot/sources/azure_data_lake.py
- viadot/tasks/azure_data_lake.py
Changed tests for `Sharepoint` and logger messages in `AzureDataLakeRemove` task. the previous ones were incorrect.
To correct the messages and pass the tests.
This PR:
> Correct log messages in AzureDataLakeRemove and tests

- tests/integration/flows/test_azure_sql_transform.py
- tests/integration/tasks/test_azure_sql.py
- viadot/tasks/azure_sql.py
Added return df
Fix a bug
This PR:
> 🐛 Fixed check column order

- CHANGELOG.md
- tests/integration/tasks/test_task_utils.py
- viadot/flows/sap_rfc_to_adls.py
- viadot/flows/sap_to_duckdb.py
- viadot/task_utils.py
Added `update_kv` and `field_to_refresh` params to `SAPRFCToADLS` and `SAPToDuckDB` flows and added `set_new_kv()` task
in `task_utils`
Enabling creating flows with changing filter values
This PR:
> ✨ Added `update_kv` and `field_to_refresh` params

- CHANGELOG.md
- viadot/task_utils.py
Added handling empty DF in `set_new_kv()` task
Fixing bug
This PR:
> 🐛 Added handling empty df

- viadot/sources/genesys.py
> 📝 Adjust documentation

- viadot/sources/genesys.py
- viadot/tasks/genesys.py
> Genesys-logging

- viadot/flows/genesys_to_adls.py
- viadot/tasks/genesys.py
change the import part of genesys.py (source)
new flow structure in genesys_to_adls.py
> 🎨 add flow in genesys_to_adls and make-up of imports in genesys (source)

- viadot/flows/genesys_to_adls.py
- viadot/tasks/genesys.py
> Revert "Genesys"

- viadot/flows/genesys_to_adls.py
> 💄 make-up  in genesys_to_adls flow

- viadot/sources/genesys.py
> 💄 change in the order of functions. genesys.py (source)

- viadot/flows/adls_to_azure_sql.py
- viadot/sources/azure_data_lake.py
- viadot/tasks/azure_data_lake.py
added a new feature in AzureDataLake class to recursively list, and improved the ADLSToAzureSQL class to upload multiple files
Required by a client.
> ADLS to SQL improvement

- CHANGELOG.md
- tests/integration/tasks/test_bcp.py
- viadot/flows/adls_to_azure_sql.py
- viadot/flows/duckdb_to_sql_server.py
- viadot/tasks/bcp.py
Changed default value of 'on_bcp_error' parameter to fail
Noticing when flow is not working properly will be easier
This PR:
> ⚡️ Changed default value of 'on_bcp_error'

- viadot/flows/adls_to_azure_sql.py
- viadot/tasks/azure_data_lake.py
changed recursive function to list adls files, and revert to the previous version in ADLSToAzureSQL Flow
AzureDataLakeList has changed the recursive method, now instead of the ls() method, it uses the find() method.
The class ADLSToAzureSQL is reverted to the previous version.
This PR:
> changed recursive function

- docker/Dockerfile
- viadot/tasks/datahub.py
Add a new task for cleaning up the `dev` environment for a more repeatable environment.
For now, the parameters are hardcoded due to lack of time.
This PR:
> Add databricks cleanup task

- requirements.txt
Added new requirements
hot fix
This PR:
> 🐛 Added protobuf

- viadot/tasks/__init__.py
Fix import error from `datahub_cleanup_task`
This PR:
> Fix import error from `datahub_cleanup_task`

- tests/integration/flows/test_sharepoint_to_adls.py
- tests/integration/tasks/test_azure_data_lake.py
- tests/integration/test_mindful.py
- tests/integration/test_outlook.py
- tests/integration/test_sftp.py
Fix a tests for release 4.10
This PR:
> 🐛 Fix tests for release 4.10

- CHANGELOG.md
- requirements.txt
Upgrading version of duckdb
Improving performance
This PR:
> ⚡️ Upgraded duckdb version

- CHANGELOG.md
- tests/unit/test_duckdb.py
- viadot/sources/duckdb.py
Added WITH to query keywords and removed comments before running DuckDB query
Added option to run query that starts with "WITH" or comments to a DataFrame
This PR:
> ✨ Added removing comments and added WITH to keywords

- .github/workflows/docker-publish.yml
- improves workflow run name to see image tag & person who triggered the run
- fixed errors
This PR:
> Improved workflow run name & fixed errors

- viadot/sources/exchange_rates.py
Update `ExchangeRates` to use new config
This PR:
> ♻️ Update `ExchangeRates` to use new config

- requirements.txt
Remove unused requirements after having removed tasks which depended on these.
This PR:
> 🔥 Remove unused requirements after having removed tasks

- viadot/sources/__init__.py
Readd Databricks to __init__
This PR:
> ♻️ Readd Databricks to __init__

- viadot/sources/__init__.py
- viadot/sources/azure_data_lake.py
> ♻️ Readding the `AzureDataLake` source

- viadot/sources/databricks.py
Adds a default cluster port to `Databricks` source
This PR:
> ✨ Add a default cluster port to `Databricks` source

- viadot/sources/databricks.py
Fixes missing info about the required `org_id` credential
This PR:
> 🐛 Add missing info about the required `org_id` credential

- viadot/exceptions.py
- viadot/sources/databricks.py
Adds a `TableDoesNotExist` exception
This PR:
> ✨ Add `TableDoesNotExist` exception

- CHANGELOG.md
- docker/docker-compose.yml
- tests/conftest.py
- tests/integration/test_azure_data_lake.py
- viadot/__init__.py
- viadot/sources/azure_data_lake.py
Adds `from_df()` method to `Azure Data Lake` source
This PR:
> Add `from_df()` method to `Azure Data Lake` source

- viadot/config.py
Adding an additional parameter `config` to functions `get_source_config` and `get_source_credentials`
Allows you to add your own `config` to the function
This PR:
> ✨ Added parameters to functions in config.py

- tests/unit/test_databricks.py
- tests/unit/test_exchange_rates.py
- viadot/exceptions.py
- viadot/sources/databricks.py
- viadot/sources/exchange_rates.py
- viadot/sources/sharepoint.py
- viadot/utils.py
Updates `Databricks` source to work with 2.0 configs
This PR:
> ♻️ Update Databricks to work with 2.0 configs

- tests/unit/test_exchange_rates.py
- viadot/sources/exchange_rates.py
Adding a column to the to_df function in the exchange reates source
Adds a column that contains information about when the data was downloaded 
This PR:
- [x ] adds new tests (if appropriate)
- [x ] updates docstrings for any new functions or function arguments (if appropriate)
- [x ] updates `CHANGELOG.md` with a summary of the changes
> ✨ Adding a column to the to_df function

- CHANGELOG.md
- viadot/sources/epicor.py
Added new columns `RequiredDate` and `CopperWeight`
Changes in Epicor view structure
This PR:
> ✨ Added `RequiredDate` and `CopperWeight`

- viadot/sources/epicor.py
- viadot/sources/mysql.py
- viadot/sources/supermetrics.py
- viadot/tasks/genesys.py
- viadot/tasks/outlook.py
- viadot/tasks/prefect_date_range.py
- viadot/tasks/sftp.py
Improved imports in viadot by deleting unused ones.
This PR:
> clean imports

- CHANGELOG.md
- viadot/task_utils.py
- viadot/utils.py
Function that gets credentials from azure Key Vault or PrefectSecret or from prefect local config.
That function will unify our way of loading credentials in connectors.
This PR:
> Credentials loader function

- CHANGELOG.md
- requirements.txt
Added avro-python3 library to requirements.txt 
New library will allow to use avro files.
This PR:
> ✨ added avro-python3 library to requirements

- viadot/tasks/duckdb.py
- viadot/tasks/sap_rfc.py
added timeout to run and defaults_from_attrs
Added timeout
This PR:
> 🎨 added timeout to run and defaults_from_attrs

- tests/unit/test_utils.py
- viadot/sources/azure_data_lake.py
- viadot/sources/databricks.py
- viadot/sources/exchange_rates.py
- viadot/sources/sharepoint.py
- viadot/sources/uk_carbon_intensity.py
- viadot/utils.py
"In this PR a decorator that adds a new column indicating the source name is added to every source to_df method"
Because we need to register inside the df the source data is coming from
This PR:
> ✨ Created decorator to include viadot source to df

- viadot/flows/outlook_to_adls.py
- viadot/sources/outlook.py
Workaround that solves outlook messages extraction issue.
This PR:
> Outlook msg fix

- CHANGELOG.md
- tests/integration/test_sap_rfc.py
- viadot/examples/sap_rfc/Dockerfile
- viadot/examples/sap_rfc/README.md
- viadot/exceptions.py
- viadot/sources/__init__.py
- viadot/sources/sap_rfc.py
- Adds SAPRFC source.
- Adds SAPRFC integration test.
- Updates sap_rfc base image to viadot:2.0a11.
Enables SAP RFC connection
This PR:
> Add SAPRFC source

- requirements.txt
- tests/unit/test_s3.py
- viadot/sources/__init__.py
- viadot/sources/redshift_spectrum.py
- viadot/sources/s3.py
> Add s3 source

- viadot/examples/sap_rfc/Dockerfile
- viadot/sources/redshift_spectrum.py
- viadot/sources/s3.py
Eliminates the need to specify credentials and resolves associated errors.
This PR:
> 🐛 Fix credential handling when not specified

- CHANGELOG.md
- tests/unit/test_task_utils.py
- viadot/flows/genesys_to_adls.py
- viadot/flows/mindful_to_adls.py
- viadot/task_utils.py
Here it is added to `task_utils.py` the task `adls_bulk_upload` used in the flows of Genesys and Mindful, but it can be also used in other flows when it is needed.
It is an improvement of the code not relevant for business but clarifies the code and makes it easy to read and use.
This PR:
> Added bulk upload to ADLS

- viadot/examples/sap_rfc/Dockerfile
- viadot/examples/sap_rfc/README.md
Improves SAP RFC viadot setup and eliminates issues with file access and permissions on Linux.
- changed the base image to the remote image to ensure there is no need to build/update viadot:dev locally
- removed setting permissions in the sap_rfc image as they have already been set in the viadot:dev. Setting permissions in sap_rfc image leads to conflicting configuration and cause issues with file access and permissions on Linux.
This PR:
> Fix sap rfc setup

- CHANGELOG.md
- tests/integration/test_mindful.py
- viadot/sources/mindful.py
- viadot/tasks/mindful.py
Was created a new connection to surveys in Mindful. Was added a new method in `Mindful` source file to create the connection and also updated `MindfulToCSV` task to create the file in order to upload it to ADLS.
Required by the client.
This PR:
> Mindful survey endpoint

- viadot/flows/genesys_to_adls.py
- viadot/flows/mindful_to_adls.py
- viadot/sources/mindful.py
Because of some PR, the code was mixed and this PR solved that problem. Renamed a parameter and changed the way `adls_bulk_upload` is imported.
Crucial
This PR:
> 🐛 fixed bugs in genesys and mindful flows.

- viadot/tasks/bigquery.py
PR is create to fix error in Bigquery task. Project_name was missing in query.
To make it work correctly.
This PR:
> 🐛 Added project_name to query

- docker/docker-compose.yml
- tests/unit/test_config.py
- viadot/config.py
Fixes handling of empty viadot config
This PR:
> 🐛 Fix handling of empty viadot config

- requirements-dev.txt
- requirements.txt
Fixes an issue with image not building because of forever resolving the huge list of boto3 versions.
Also updating some dev requirements while I'm at it.
This PR:
> 📌 Fix boto dependency hell

- requirements.txt
Should fix issues with image building.
This PR:
> 📌 Fix boto to particular version

- .github/workflows/docker-publish.yml
Remove ARM architecture as it doubles build time and causes some issues.
This PR:
> Remove ARM architecture

- requirements-dev.txt
- requirements.txt
> Remove old dependencies

- requirements.txt
> ➕ Add missing `pyyaml` dependency

- .dockerignore
- requirements.txt
Add another missing dependency after changing base image from `prefect` to `python`
This PR:
> ➕ Add `pydantic` dependency

- viadot/__init__.py
> ⬆️ Bump `viadot` package version

- tests/conftest.py
- tests/unit/test_sharepoint.py
- viadot/sources/__init__.py
- Added missing test for `Sharepoint.download_file()`
This PR:
> ✨ Add `test_download_file()` test for `Sharepoint` source

- CONTRIBUTING.md
Minor change to test the 2.0 docker build action
This PR:
> 📝 Minor docs change

- tests/integration/tasks/test_outlook.py
- tests/integration/test_outlook.py
- viadot/flows/outlook_to_adls.py
- viadot/sources/outlook.py
- viadot/tasks/outlook.py
More test have been added to the file `test_outlook.py`
low
This PR:
> ✅ updated test for outlook.

- CHANGELOG.md
- tests/unit/test_databricks.py
- viadot/sources/databricks.py
Pr includes fixing the overwriting of tables in Databricks. Previously, a table was overwritten if it had the same number of columns. However, if, for example, a metadata column was added, overwriting was not possible. This has been fixed in this PR. I have also added a unit test for this case. It also seems to me that the tests need refactoring here, which is why I have created a user story for this [ user story ](https://dev.azure.com/VELUX-IT-Dev/AIA/_backlogs/backlog/AIA%20Team/Epics/?workitem=131621).
This is important because any change to the table schema will cause an error if an attempt is made to overwrite it.
This PR:
- [ x ] adds new tests (if appropriate)
- [  ] updates docstrings for any new functions or function arguments (if appropriate)
- [ x ] updates `CHANGELOG.md` with …
> Databricks replace bug

- CHANGELOG.md
- requirements.txt
- tests/unit/test_genesys.py
- viadot/sources/__init__.py
- viadot/sources/genesys.py
The Genesys source was moved from viadot 1 to viadot 2. I did not do refactoring due to the need to deliver the code before Friday. Refactoring will be done in the next PR
This PR:
> Genesys source migration

- CHANGELOG.md
- viadot/sources/genesys.py
Added creation of a new event loop in the genesys_generate_exports function. In prefect it is necessary to create an event_loop if running async code.
This PR:
> Genesys bug fix

- CHANGELOG.md
- viadot/sources/sap_rfc.py
Added close_connection() function to sap_rfc source
Connection to sap is not closing after running .to_df()
This PR:
> 🐛 Added closing connection

- CHANGELOG.md
- tests/integration/test_business_core.py
- viadot/sources/__init__.py
- viadot/sources/base.py
- viadot/sources/business_core.py
- viadot/tasks/__init__.py
- viadot/tasks/business_core.py
New connector for Business Core API. Source and task. Source will be developed for further views when schema will be delivered (marked as todo). 
Added to_parquet() in base.py
New data source
This PR:
> Business Core connector

- CHANGELOG.md
- docs/howtos/howto_migrate_sources_tasks_and_flows.md
Refined the formatting and content of the viadot migration docs by adding hyperlinks, fixing typos and removing unnecessary parts.
It serves to bring the viadot migration docs to their completion.
This PR:
> 📝 Refined viadot migration docs

- config.yaml.example
- docker/docker-compose.yml
> Cleanup compose

- CHANGELOG.md
- tests/unit/test_databricks.py
- tests/unit/test_utils.py
- viadot/sources/databricks.py
- viadot/utils.py
Includes corrections from PR (#682 ). A new PR was created due to the number of changes on the 2.0 branch
Closes https://github.com/dyvenia/viadot/issues/681. Added a fix inside the create table from_pandas() function to change the data types in rows of pandas.object columns to string.
In certain cases, the lack of a change will result in an error in uploading data to databricks
This PR:
> Databricks pandas types casting

- CHANGELOG.md
- viadot/sources/base.py
- viadot/sources/business_core.py
Added handling new view
new feature
This PR:
> ✨ Added GetPendingSalesOrderData view

- docker/Dockerfile
> ✨ Add MSSQL ODBC driver to image

- CHANGELOG.md
- requirements.txt
- tests/integration/flows/test_sap_bw_to_adls.py
- tests/integration/tasks/test_sap_bw.py
- tests/integration/test_sap_bw.py
- viadot/flows/__init__.py
- viadot/flows/sap_bw_to_adls.py
- viadot/sources/__init__.py
- viadot/sources/sap_bw.py
- viadot/tasks/__init__.py
- viadot/tasks/sap_bw.py
The PR contains code for connection and data extraction from SAP BW.
Code allows for the direct connection with SAP BW, instead of using ADF pipelines.
This PR:
> added new connector SAPBW

- CHANGELOG.md
- tests/integration/flows/test_sql_server_to_parquet.py
- viadot/flows/__init__.py
- viadot/flows/sql_server_to_parquet.py
Added `SQLServerToParquet` flow.
New flow for transferring data from SQLServer database to Parquet file
This PR:
> Added `SQLServerToParquet` flow.

- CHANGELOG.md
- tests/integration/tasks/test_genesys_task.py
- viadot/flows/genesys_to_adls.py
- viadot/tasks/genesys.py
Added new features for GET method from genesys source. PR realted to WebMsg project.
This PR:
> ✨ Added new function for the GET method

- CHANGELOG.md
- tests/integration/flows/test_vidclub_to_adls.py
- viadot/flows/__init__.py
- viadot/flows/vid_club_to_adls.py
- viadot/sources/vid_club.py
- viadot/tasks/vid_club.py
Flow class for ingesting data from Vid Club API to Azure Data Lake as .parquet or .csv file.
With flow class we'll be able to schedule automated data downloads directly to ADLS.
This PR:
> Add `VidClubToADLS` flow

- .gitignore
> Added to .gitignore new assumptions

- CHANGELOG.md
- requirements.txt
- tests/unit/test_utils.py
- viadot/utils.py
Added function to `utils` as a decorator. The function adds an additional column with metadata.
For now only `_viadot_source` is added. It should be applied to the source 'to_df()' method.
It is important to align to what is in viadot 2.0. `_viadot_downloaded_at_utc` is added on the Flow level but `_viadot_source` is added using this decorator.
This PR:
> ✨ Added `add_viadot_metadata_columns` function

- CHANGELOG.md
- docker/Dockerfile
> ✨ Updated Dockerfile

- tests/unit/test_task_utils.py
- viadot/task_utils.py
> ✨ Added test for column sum+ tests for validate_df

- tests/integration/flows/test_cloud_for_customers_report_to_adls.py
- viadot/flows/cloud_for_customers_report_to_adls.py
- viadot/sources/cloud_for_customers.py
Added `validation_df_dict` to CloudForCustomersReportToADLS flow class
data validation
This PR:
> C4C `validate_df` parameter

- tests/integration/flows/test_mediatool_to_adls.py
- viadot/flows/mediatool_to_adls.py
Added new parameter to flow class
new functionality to check data
This PR:
> added validate_df task to MediatoolToADLS flow

- tests/integration/flows/test_vidclub_to_adls.py
- viadot/flows/vid_club_to_adls.py
Added `validate_df` task to `VidClubToADLS` class to let user define tests for validating the output dataframe.
This PR:
> added `validate_df` task to `VidClubToADLS` flow

- tests/integration/flows/test_sap_rfc_to_adls.py
- viadot/flows/sap_rfc_to_adls.py
added `validate_df task` to SAPRFCToADLS flow
New parameter/task for validating data
This PR:
> added `validate_df task` to SAPRFCToADLS flow

- tests/integration/flows/test_customer_gauge_to_adls.py
- viadot/flows/customer_gauge_to_adls.py
Added `validate_df` task to `CustomerGaugeToADLS` class to let user define tests for validating the output dataframe.
This PR:
> added `validate_df` task to `CustomerGaugeToADLS` class

- tests/integration/flows/test_sap_bw_to_adls.py
- viadot/flows/sap_bw_to_adls.py
- viadot/sources/sap_bw.py
- viadot/tasks/sap_bw.py
Added `validate_df` task to `SAPBWToADLS` class to let user define tests for validating the output dataframe.
This PR:
> added `validate_df` task to `SAPBWToADLS` class

- tests/integration/flows/test_salesforce_to_adls.py
- viadot/flows/salesforce_to_adls.py
> Added validate_df to SalesforceToADLS

- tests/integration/test_customer_gauge.py
- tests/integration/test_epicor.py
- tests/integration/test_genesys.py
- tests/integration/test_hubspot.py
- tests/integration/test_mediatool.py
- viadot/sources/epicor.py
- viadot/sources/mediatool.py
PR is created to improve test coverage in viadot source packages.
List of classes to which tests are added:
* Genesys
* Mediatool
* Hubspot
* Customer Gauge
* Epicor
To have better test coverage.
This PR:
> Improve test coverage for viadot  source package

- CHANGELOG.md
- requirements.txt
Add new libraries nltk and sklearn to the requirements
This PR:
> ✨ Add new requirements

- tests/integration/test_sharepoint.py
Short fix for typo in sharepoint tests
Important for last changes merge
This PR:
> Fixed typo in tests

- viadot/tasks/genesys.py
> Revert of changes for desired columns

- viadot/sources/sap_bw.py
added missing conn.close()
This PR:
> added conn.close after each session to sappw

- viadot/sources/minio.py
> ✨ Add `partition_cols` param to `Minio.from_df()`.

- viadot/__init__.py
> Update version to 2.0a15

- viadot/sources/vid_club.py
Summary
---
Cleaning vid_club connector code.
Importance
---
Deletes unused imports, changes the way response data is normalized after being fetched in API call.
Checklist
---
This PR:
> Fixed json normalize

- viadot/sources/minio.py
- viadot/sources/trino.py
> ✨ Optimize `MinIO` and `Trino` sources

- CHANGELOG.md
- viadot/sources/genesys.py
- viadot/tasks/genesys.py
New viewtype added to Genesys.
Required by client.
This PR:
> New Viewtype agent timeline

- requirements.txt
> change pandas-gbq version

- requirements.txt
> test dependencies

- viadot/__init__.py
> ⬆️ Bump version

- viadot/sources/minio.py
> Implement `recursive` param in `MinIO.rm()`

- viadot/__init__.py
> 🔖 Bump version

- viadot/__init__.py
- viadot/sources/trino.py
> Trino connection context manager

- viadot/__init__.py
> 🚀 Bumped viadot2 version to `2.0a20`

- viadot/flows/adls_to_azure_sql.py
Changes upstream order for df_validation
Fixes issue of loading data into sql table even if validation check is failed
This PR:
> changed upstream order for df_validation

- .vscode/extensions.list
- .vscode/settings.json
- pyproject.toml
- requirements-dev.lock
- requirements.lock
> Bump `azure-identity`

- docker/Dockerfile
> 🐛 Fix pip not installing to viadot user's `.local` dir

- docker/Dockerfile
> 🐛 Fix Dockerfile build failing due to file permissions

- viadot/flows/transform_and_catalog.py
- viadot/tasks/luma.py
It is created to improve the `TransformAndCatalogToLuma` process and add new flags to the `LumaIngest`
There are 2 github issues:
#858 
#857 
This PR:
> Modify `TransformAndCatalogToLuma` process and commands

- .pre-commit-config.yaml
- mkdocs.yml
> 🐛 Fix MkDocs build failing due to incorrect YAML parsing

- pyproject.toml
- requirements-dev.lock
- requirements.lock
> ⬆️ Relax sql-metadata version requirement

- CHANGELOG.md
- docker/Dockerfile
- docs/references/sources/sql_sources.md
- pyproject.toml
- requirements-dev.lock
- requirements.lock
- src/viadot/orchestration/prefect/flows/__init__.py
- src/viadot/orchestration/prefect/flows/sql_server_to_minio.py
- src/viadot/orchestration/prefect/tasks/__init__.py
- src/viadot/orchestration/prefect/tasks/minio.py
- src/viadot/orchestration/prefect/tasks/sql_server.py
- src/viadot/orchestration/prefect/utils.py
- src/viadot/sources/__init__.py
- src/viadot/sources/minio_source.py
- src/viadot/sources/sql_server.py
- tests/orchestration/prefect_tests/flows/test_sql_server_to_minio.py
- tests/orchestration/prefect_tests/integration/test_minio.py
- tests/orchestration/prefect_tests/integration/test_sql_server.py
- tests/viadot_tests/integration/test_sql_server.py
Prefect 2 connector for SQLServer to MinIO. 
Handling new credential blocks - Secret and DatabaseCredentialBlock
New data source
This PR:
> SQLServer to MinIO

- pyproject.toml
- requirements-dev.lock
- requirements.lock
> 🐛 Fixed DuckDB dependency 

- docker/docker-compose.yml
- pyproject.toml
> 🚀 Relase `viadot 2.0.0-beta.1`

- pyproject.toml
- requirements-dev.lock
- requirements.lock
Added `O365` to requirements
There is a missing O365 library that makes the registration of deployment impossible.
This PR:
> ✨ Added 0365

- .github/dependabot.yml
> 🔥 Remove Dependabot since it's not used on the main branch anyway

- .github/workflows/cd.yml
- CONTRIBUTING.md
> 🐛 Fix release workflow

- .github/workflows/cd.yml
- CONTRIBUTING.md
- pyproject.toml
> 🧑‍💻 Improve cd workflow

- .github/workflows/cd.yml
> ✨ Add CD workflow for 2.0 branch

- pyproject.toml
> 🔖Version bump 2.1.5

- CHANGELOG.md
- src/viadot/orchestration/prefect/flows/__init__.py
- src/viadot/orchestration/prefect/flows/sql_server_to_parquet.py
- src/viadot/orchestration/prefect/tasks/bcp.py
- src/viadot/orchestration/prefect/tasks/sql_server.py
Adeed sql_serer_to_parquet flow and fixed bcp task
new connector and fix
This PR:
> ✨ Add `sql_server_to_parquet` flow

- src/viadot/orchestration/prefect/tasks/task_utils.py
Fix path in `df_to_csv` and `df_to_parquet` tasks
fix
This PR:
> 🐛 Fix `df_to_csv` and `df_to_parquet` tasks

- src/viadot/orchestration/prefect/utils.py
Bugfix for wrong func selection if block_type = 'Secret'
This PR:
> 🐛 Bug fix for if statement for secret block type selection

- CONTRIBUTING.md
- pyproject.toml
> 🔖 Version bump 2.1.6

- .vscode/settings.json
- pyproject.toml
> 🐛 Fix PyPI release workflow

- .github/workflows/detect-and-tag-new-version.yml
- CONTRIBUTING.md
- pyproject.toml
Improve the release process further by eliminating the need to manually create & push tag as part of the release process.
> 🧑‍💻 Further automate CD

- .github/workflows/detect-and-tag-new-version.yml
> 🐛 Fix `git tag` step failing

- .github/workflows/detect-and-tag-new-version.yml
Fix release process not triggered due to undocumented GitHub triggers behavior.
> 🐛 Fix release process not getting triggered

- .github/workflows/detect-and-tag-new-version.yml
- pyproject.toml
Use dyvenia bot's token to try and fix `cd.yml` not being triggered despite a new tag being created.
> 🐛 Fix release trigger workflow

- .github/workflows/cd.yml
- .github/workflows/detect-and-tag-new-version.yml
- pyproject.toml
> 🧑‍💻 Release trigger action - second approach

- .github/workflows/detect-and-tag-new-version.yml
- pyproject.toml
Use Ludovico bot's token, rather than unnamed other dyvenia bot's.
> ♻️ Switch `detect-and-tag-new-version` workflow's token

- .pre-commit-config.yaml
- pyproject.toml
- src/viadot/orchestration/prefect/flows/__init__.py
- src/viadot/orchestration/prefect/flows/bigquery_to_adls.py
- src/viadot/orchestration/prefect/tasks/__init__.py
- src/viadot/orchestration/prefect/tasks/bigquery.py
- src/viadot/sources/__init__.py
- src/viadot/sources/bigquery.py
- tests/integration/test_bigquery.py
- tests/unit/test_bigquery.py
Bigquery connector migration from viadot 1 to viadot 2.
Required by the migration project.
This PR:
> Bigquery migration2

- src/viadot/orchestration/prefect/tasks/git.py
Added handling gitlab token in git task - change gitlab url when token is present
handling gitlab
This PR:
> ✨ Add gitlab handling - token

- .pre-commit-config.yaml
- src/viadot/orchestration/prefect/flows/__init__.py
- src/viadot/orchestration/prefect/flows/salesforce_to_adls.py
- src/viadot/orchestration/prefect/tasks/__init__.py
- src/viadot/orchestration/prefect/tasks/salesforce.py
- src/viadot/sources/__init__.py
- src/viadot/sources/salesforce.py
- tests/integration/test_salesforce.py
- tests/unit/test_salesforce.py
SalesForce connector migration from viadot 1 to viadot 2.
Required by the migration project.
This PR:
> Salesforce migration2

- CONTRIBUTING.md
> 📝 Improve the pre-commit section of contributing guide

- pyproject.toml
- src/viadot/orchestration/prefect/flows/transform.py
Remove unused part of the code
clenup
This PR:
> 🔥 Remove dbt docs task from `Transfrom` flow

- pyproject.toml
- requirements-dev.lock
- requirements.lock
> ➕ Add missing `aiohttp` dependency

- src/viadot/sources/sap_rfc.py
Bugfix to prevent flows from crashing when there is no data for one of the columns chunk.
Closes #https://github.com/dyvenia/werfen-project/issues/337
This PR:
> 🐛Added if empty check to prevent not in index errors

- docs/developer_guide/creating_a_prefect_flow.md
- src/viadot/orchestration/prefect/flows/__init__.py
- src/viadot/orchestration/prefect/flows/exchange_rates_to_redshift_spectrum.py
- src/viadot/orchestration/prefect/tasks/exchange_rates.py
> ✨ Add Exchange Rates API to Redshift Spectrum flow

- pyproject.toml
> 🔖 Version bump 2.1.18

- pyproject.toml
Bumped viadot version to `2.1.19`
This PR:
> 🔖 Version bump 2.1.19

- src/viadot/orchestration/prefect/flows/genesys_to_adls.py
- src/viadot/orchestration/prefect/tasks/genesys.py
- src/viadot/sources/genesys.py
- tests/unit/test_genesys.py
Fixed a potential problem in Genesys Connector.
This PR:
> 📝 `Genesys` source - document the delay in between API calls

- pyproject.toml
> 🐛 Fix coverage counting unit test files

- src/viadot/config.py
> ♻️ Simplify the `get_source_config()` util

- pyproject.toml
> ⬆️ Upgrade `pyrfc` to 3.x

- pyproject.toml
- src/viadot/sources/epicor.py
> 🎨 Change append to concat in Epicor source

- .secrets.baseline
- src/viadot/sources/customer_gauge.py
- src/viadot/sources/epicor.py
- src/viadot/sources/genesys.py
- src/viadot/sources/hubspot.py
- src/viadot/sources/outlook.py
- src/viadot/sources/redshift_spectrum.py
- src/viadot/sources/sap_bw.py
- src/viadot/sources/supermetrics.py
- tests/unit/test_customer_gauge.py
- tests/unit/test_genesys.py
- tests/unit/test_hubspot.py
- tests/unit/test_outlook.py
> ✨ Add s3 endpoint param to redshift

- docs/references/orchestration/prefect/flows.md
- docs/references/orchestration/prefect/tasks.md
- docs/references/sources/api.md
- src/viadot/orchestration/prefect/flows/__init__.py
- src/viadot/orchestration/prefect/tasks/__init__.py
- src/viadot/sources/__init__.py
> 📝 Add docs for the `Eurostat` source & tasks

- src/viadot/sources/cloud_for_customers.py
It was a bug. It should be fixed to properly authenticate.
This PR:
> ✨ Insert getting password for `C4C` source

- src/viadot/sources/redshift_spectrum.py
> 🐛 Fix `boto3.Session` not having a `endpoint_url` param

- src/viadot/sources/epicor.py
Added columns to base model for line item deatail
more precise data
This PR:
> ✨ Add columns in `LineItemDetail` model for `Epicor` source

- src/viadot/sources/business_core.py
Add condition if  `filters` parameter is None
Fixed errors
This PR:
> 🐛 Fix `filters` parameter for `BusinessCore` source

- docs/getting_started.md
> 📝 Fix Rye links in docs

- pyproject.toml
> 🔖 Version bump to 2.1.25

- pyproject.toml
> 🔖 Version bump to 2.1.26

- pyproject.toml
- src/viadot/orchestration/prefect/flows/business_core_to_parquet.py
Removed unused parameter from `business_core_to_parquet` flow.
Clean-up
This PR:
> 🔥 Removed parameter from `business_core_to_parquet` flow

- pyproject.toml
> 🔖 Version bump to 2.1.28

- src/viadot/orchestration/prefect/tasks/salesforce.py
- src/viadot/sources/salesforce.py
- tests/unit/test_salesforce.py
Prefect migration 2.0 backlog changes for Salesforce 2.0, related to issues:
- #1050 
- #1055 
Clean code
This PR:
> ♻️ Refactor Salesforce, 2.0 backlog issues

- src/viadot/orchestration/prefect/tasks/bigquery.py
- src/viadot/sources/bigquery.py
- tests/unit/test_bigquery.py
Prefect migration 2.0 backlog changes for BigQuery, related to issues:
- #1049 
- #1048 
Clean code
This PR:
> ♻️ Refactor BigQuery, 2.0 backlog issues

- src/viadot/orchestration/prefect/flows/transform_and_catalog.py
> 🥅  Add some retries to the `dbt deps` task in T&C flow

- pyproject.toml
Release 2.2.1
Introduces new filtering options for dynamic dates.
This PR:
> 🔖 Bump version - 2.2.1

- pyproject.toml
- requirements-dev.lock
- requirements.lock
Adding 2 new libraries for Prefect messages handling via Slack.
"tabulate>=0.9.0",
"prefect-slack<=0.2.7"
> added tabulate and prefect-slack libs to pyproject

- src/viadot/orchestration/prefect/flows/__init__.py
- src/viadot/orchestration/prefect/flows/sharepoint_list_to_redshift_spectrum.py
- src/viadot/orchestration/prefect/tasks/__init__.py
- src/viadot/orchestration/prefect/tasks/redshift_spectrum.py
- src/viadot/orchestration/prefect/tasks/sharepoint.py
- src/viadot/sources/__init__.py
- src/viadot/sources/sharepoint.py
- tests/unit/test_sharepoint_list.py
Implement SharePoint List connector source with corresponding Prefect task and flow, along with unit tests for data retrieval functionality.
This PR is important because it introduces a new data source connector for SharePoint Lists, enhancing the ability to integrate SharePoint data into workflows. It provides users with the capability to fetch data from specific lists, filter output by fields, and apply custom queries, which is crucial for efficient data management and analysis.
This PR:
CLOSES https://github.com/dyvenia/werfen-project/issues/1435 [#1453](https://github.com/dyvenia/werfen-project/issues/1453)
> ✨ Added Sharepoint list source class

- pyproject.toml
> 🔖 Bump version to - 2.2.3

- src/viadot/sources/epicor.py
Added columns to base model for `LineItemDetail`
Columns needed
This PR:
> ✨ Add columns in `LineItemDetail` model for Epicor source

- pyproject.toml
> 🔖 Bump version to - 2.2.5

- pyproject.toml
- src/viadot/orchestration/prefect/flows/sap_to_redshift_spectrum.py
- src/viadot/orchestration/prefect/tasks/sap_rfc.py
- src/viadot/orchestration/prefect/utils.py
- src/viadot/sources/sap_rfc.py
- tests/unit/orchestration/prefect/test_utils.py
- tests/unit/test_sap_rfc_2.py
This PR introduces the `DynamicDateHandler` class functionality to `sap_to_redshift_spectrum` to proccess date symbols/placeholders inside query.
Enable  support  for date processing in sap source. 
This PR:
> ✨ Add `DynamicDateHandler` functionality to `sap_to_redshift_spectrum`  flow

- src/viadot/sources/smb.py
- tests/unit/test_smb.py
Add missing options and handling specific cases to SMB connector.
Add a few changes to reduce the number of required parameters and make them easier to apply.
Add skipping temp files uploaded to the source server.
This PR:
> ✨ Refactor `SMB` connector

- mkdocs.yml
Updated mkdocs footer. After migration to static site updated year in copyright section.
This PR:
> Updated year in a footer of mkdocs

- pyproject.toml
> 🔖 Bump version to `2.2.7`

- pyproject.toml
> 🔖 Bump version to `2.2.8`

- src/viadot/sources/smb.py
- tests/unit/test_smb.py
The connection managements needs to be changed to identify potential problems. 
Added improved error handling to notify users clearly about any issues encountered during the process, enhancing transparency and user experience.
Some of files are skipped because of the error and lack of errors handling. 
This PR:
> ✨ SMB - Improve error handling and connection management

- pyproject.toml
Bump `viadot` version to `2.2.10`
> 🔖 Bump version to `2.2.10`

- pyproject.toml
> 🔖 Bump version to 2.2.11

- pyproject.toml
- src/viadot/sources/sap_rfc.py
Updated dataframe filtering to use non-aliased columns.
Ensures dataframe columns stay consistent with the query and its aliases.
This PR:
> 🐛  Fix dataframe filtering when aliased columns are applied

- pyproject.toml
> 🔖 Release 2.2.15
